language: python
dist: focal
python:
  - "3.9"

services:
  - docker

script:
  - docker build --build-arg SENTRY_RELEASE_ID=$TRAVIS_BUILD_NUMBER -t marcsello/ponyhug-backend:$TRAVIS_BUILD_NUMBER .
  - docker tag marcsello/ponyhug-backend:$TRAVIS_BUILD_NUMBER marcsello/ponyhug-backend:latest

deploy:
  skip_cleanup: true
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push marcsello/ponyhug-backend
  on:
    branch: master
