language: python
dist: bionic
python:
  - "3.8"

services:
  - docker

install:
  - pip3 install pylint
  - pip3 install -r requirements.txt

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.kmlabz.com

after_success:
  - docker build -t registry.kmlabz.com/ponyhug/backend .

deploy:
  skip_cleanup: true
  provider: script
  script: docker push registry.kmlabz.com/ponyhug/backend
  on:
    branch: master
