language: python
dist: bionic
python:
  - "3.8"

services:
  - docker

install:
  - pip3 install pylint
  - pip3 install -r requirements.txt

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.kmlabz.com

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
