networks:
  ponyhug:
    external: false

services:
  test-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=ponyhug
      - POSTGRES_PASSWORD=ponyhug
      - POSTGRES_DB=ponyhug
    networks:
      - ponyhug
    volumes:
      - ./postres-volume:/var/lib/postgresql/data

  ponyhug-backend:
    build: .
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://ponyhug:ponyhug@test-db:5432/ponyhug"
      JWT_SECRET_KEY: "test"
    depends_on:
      - postgres
    networks:
      - ponyhug
    ports:
      - "127.0.0.1:8080:8080"
